# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

defaults:
  run:
    shell: bash
    working-directory: web

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"
      - name: Clean install dependencies
        run: npm ci
      - name: Build application
        run: npm run build --if-present
  lint:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./web
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"
      - name: Clean install dependencies
        run: npm ci
      - name: Lint with ESLint
        run: npm lint --if-present
  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: ./web
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"
      - name: Clean install dependencies
        run: npm ci
      - name: Test with test runner
        run: npm test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./web
    strategy:
      matrix:
        node-version: 18.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"
      - name: Clean install dependencies
        run: npm ci
      - name: Deploy to server
        run: npm deploy --if-present